api:
  identifier: 'anydev-authserver-microservice'
  port: 5001

logger:
  options:
    level: trace

mongodb:
  url: 'mongodb://127.0.0.1:27017'
  database: 'anydev'
  options:
    useUnifiedTopology: true
    useNewUrlParser: true